version: '3.8'

services:
  # Backend Service
  backend:
    image: your-backend-image:latest  # Replace with your actual backend image
    container_name: ecommerce-backend
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
      - PORT=8081
      - JWT_SECRET=your-jwt-secret-key
      - DATABASE_URL=your-database-connection-string
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Frontend Service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8081
    depends_on:
      - backend
    networks:
      - ecommerce-network
    restart: unless-stopped

  # Nginx Reverse Proxy (Optional - for production)
  nginx:
    image: nginx:alpine
    container_name: ecommerce-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - ecommerce-network
    restart: unless-stopped

networks:
  ecommerce-network:
    driver: bridge

volumes:
  # Add any persistent volumes if needed
  # database-data:
  #   driver: local
